name: Build Caesium Image Compressor
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache libcaesium
        id: cache-libcaesium
        uses: actions/cache@v3
        env:
          cache-name: cache-libcaesium
        with:
          path: ${{github.workspace}}/build-${{ runner.os }}/libcaesium-prefix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/libcaesium.conf') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.0.*'
          version: '6.5.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qtimageformats'
          cache: true

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build-${{ runner.os }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-${{ runner.os }} --config Release --target caesium_image_compressor

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache libcaesium
        id: cache-libcaesium
        uses: actions/cache@v3
        env:
          cache-name: cache-libcaesium
        with:
          path: ${{github.workspace}}/build-${{ runner.os }}/libcaesium-prefix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/libcaesium.conf') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.0.*'
          version: '6.5.1'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          modules: 'qtimageformats'
          cache: true

      - name: Configure CMake
        run: cmake -B build_dir -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -DLIBSSH_INCLUDE_DIR=/usr/local/opt/openssl/ -DCMAKE_BUILD_TYPE=Release -B ${{github.workspace}}/build-${{ runner.os }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-${{ runner.os }} --config Release --target caesium_image_compressor

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache libcaesium
        id: cache-libcaesium
        uses: actions/cache@v3
        env:
          cache-name: cache-libcaesium
        with:
          path: ${{github.workspace}}/build-${{ runner.os }}/libcaesium-prefix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/libcaesium.conf') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.0.*'
          version: '6.5.1'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtimageformats'
          cache: true

      - name: Configure CMake
        run: cmake -B build_dir -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -DCMAKE_BUILD_TYPE=Release -B ${{github.workspace}}/build-${{ runner.os }}

      - name: Build
        run: cmake --build ${{github.workspace}}/build-${{ runner.os }} --config Release --target caesium_image_compressor