name: Build Caesium Image Compressor
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.4'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw81'
          dir: ${{ github.workspace }}/qt/
          archives: "qtimageformats"
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          setup-python: 'false'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -DWINSPARKLE_INCLUDE_DIR='${{github.workspace}}'/winsparkle -G "CodeBlocks - MinGW Makefiles" -B '${{github.workspace}}'/build

      - name: Build
        run: cmake --build '${{github.workspace}}'/build --config Release --target caesium_image_compressor