name: Build Caesium Image Compressor
on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.0.*'
          version: '6.4.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qtimageformats'
          cache: true

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target caesium_image_compressor

      - name: Run
        run: "${{github.workspace}}\build\Caesium Image Compressor.exe" --version