name: Build Caesium Image Compressor
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache libcaesium
        id: cache-libcaesium
        uses: actions/cache@v3
        env:
          cache-name: cache-libcaesium
        with:
          path: ${{github.workspace}}/build/libcaesium-prefix
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/libcaesium.conf') }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.0.*'
          version: '6.4.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qtimageformats'
          cache: true

      - name: Install Rust target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="${{env.Qt6_Dir}}" -G "CodeBlocks - MinGW Makefiles" -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --target caesium_image_compressor